info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    service-url:
        defaultZone: http://discovery-server.graylog.zone:8761/eureka

#zuul:
#  ignoredServices: "*"
#  routes:
#    productcomposite:
#      path: /productcomposite/**
#      stripPrefix: false

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
