spring:
  datasource:
    url: jdbc:mysql://host:port/database
    username: username
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jmx:
    enabled: false

eureka:
  client:
    service-url:
        defaultZone: http://discovery-server.graylog.zone:8761

#logging:
#  level:
#    net.maurerit: DEBUG
server:
  tomcat:
    max-threads: 80
